version: '3'
services:
  web:
    image: registry.bro.engineering/checkmed/checkmed:master
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres@db/postgres
      SMTP_SERVER: exim_1
      SMTP_PORT: 25
      SMTP_DOMAIN: checkmed.net
      SMTP_EMAIL_FROM: noreply@checkmed.net
    env_file: .env
    depends_on:
    - db
    ports:
    - 80:80

  db:
    image: postgres:9.6-alpine

  exim:
    image: elsdoerfer/exim-sender
    environment:
      PRIMARY_HOST: checkmed.net
      ALLOWED_HOSTS: 172.17.0.0/16
