# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f230fd09406f0dc6702c91457b5fff13bb4302a4fc2cac379b0bb833f249f1b92ed5b1a1f77c0edef30b91653c2715604dbe400a463cda7e4a18e289f9670dd

test:
  secret_key_base: f26fe78085280d792247f074f0a4a9afaec6273e2624bc8bbd98d7d9cfc5d5fd122f89d8938d600e57ca8b74dbbb1108e7ca095b2f74a87ef7eb4c564acecdda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE", "dummy") %>
  # The dummy fallback is needed for `rake assets:precompile` command
